name: Push Changes to Azure Repo

on:
  push:
    branches:
      - develop

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2

    - name: Push to Azure DevOps Repository
      run: |
        git remote add azure https://mywebapp4free@dev.azure.com/mywebapp4free/MyWebApp/_git/MyWebApp
        git push azure develop
      env:
        AZURE_REPO_TOKEN: ${{ secrets.AZURE_REPO_TOKEN }}
